services:
  - type: web
    name: gljive-app
    env: elixir
    repo: https://github.com/AnaOsk/gljive
    branch: main
    buildCommand: >
      mix deps.get &&
      mix compile &&
      mix assets.deploy
    startCommand: MIX_ENV=prod mix phx.server
    envVars:
      - key: MIX_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: gljive-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
    buildFilter:
      paths:
        - "*"
databases:
  - name: gljive-db
    databaseName: gljivedb
    user: gljiveuser
    plan: free
